// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHmeTITeBVdy5P5Zn0D6b-DNPAQteGJ6M',
    appId: '1:901663392605:web:ce02a29f44665eae8fdeb4',
    messagingSenderId: '901663392605',
    projectId: 'commonai-app',
    authDomain: 'commonai-app.firebaseapp.com',
    storageBucket: 'commonai-app.appspot.com',
    databaseURL: 'https://commonai-app-default-rtdb.firebaseio.com',
    measurementId: 'G-WVF7F8R9VC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjDWF69UZaC9lCNUymh93reiGjJwCwBcQ',
    appId: '1:901663392605:android:b13732a9759d28338fdeb4',
    messagingSenderId: '901663392605',
    projectId: 'commonai-app',
    storageBucket: 'commonai-app.appspot.com',
    databaseURL: 'https://commonai-app-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGePGtYxOUSEuGNWJ5wAinhRQfteqodZw',
    appId: '1:901663392605:ios:d22e4d93460ccc028fdeb4',
    messagingSenderId: '901663392605',
    projectId: 'commonai-app',
    storageBucket: 'commonai-app.appspot.com',
    databaseURL: 'https://commonai-app-default-rtdb.firebaseio.com',
    iosBundleId: 'com.example.commontableAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGePGtYxOUSEuGNWJ5wAinhRQfteqodZw',
    appId: '1:901663392605:ios:d22e4d93460ccc028fdeb4',
    messagingSenderId: '901663392605',
    projectId: 'commonai-app',
    storageBucket: 'commonai-app.appspot.com',
    databaseURL: 'https://commonai-app-default-rtdb.firebaseio.com',
    iosBundleId: 'com.example.commontableAiApp',
  );
}
